site_name: "Qandle AI Docs"
site_url: https://docs.qandle.ai
repo_url: https://github.com/sillytry/qandle.ai
repo_name: sillytry/qandle.ai
copyright: Copyright &copy; 2025 Qandle AI
extra_css:
    - overrides/stylesheets/extra.css
theme:
  name: material
  palette:
    # Palette toggle for dark mode (primary theme to match your design)
    - scheme: slate
  features:
    - navigation.sections
    - navigation.indexes
    - search.highlight
    - content.code.copy
    - navigation.footer

# Navigation structure - All sections will appear in the left sidebar
nav:
  - Home: index.md
  - Go to dashboard: https://www.qandle.ai/home
  - Join Discord: https://discord.gg/hcMZuuaVtq
  - GETTING STARTED:
    - Introduction: getting-started/introduction.md
    - Quick Start: getting-started/quickstart.md
  - API:
    - /GET Symbol: api/get-symbol.md
  - TUTORIALS:
    - Integrate with Langchain: tutorials/langchain.md
    - Example Prompts: tutorials/prompts.md
  - INTEGRATION:
    - Python: integration/python.md
    - Node.js: integration/nodejs.md
    - MCP : "integration/mcp-server.md"

# Extensions
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sillytry/qandle.ai
    - icon: fontawesome/brands/discord
      link: https://discord.gg/hcMZuuaVtq
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/QandleAI/
    - icon: material/language-python
      link: https://pypi.org/project/qandle-ai/
    - icon: material/nodejs
      link: https://www.npmjs.com/package/qandle-ai